import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

import Header from '@/components/header'
import Footer from '@/components/footer'
import { ThemeProvider } from '@/components/theme-provider'
import Providers from './providers'
import './globals.css'
import { Locale, i18n } from '@/i18n.config'

import './styles.css'

import { config } from '@fortawesome/fontawesome-svg-core';
import '@fortawesome/fontawesome-svg-core/styles.css';
config.autoAddCss = false;


const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})
export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}


export default function RootLayout({
  children,
  
}: Readonly<{
  children: React.ReactNode
  
}>) {
  return (
    <html 
      className='scroll-smooth antialiased'
      suppressHydrationWarning >
      <body className={`flex min-h-screen flex-col ${inter.className}`}>
         <Providers>
         <Header />
          <main className='grow'>{children}</main>
          <Footer />
        </Providers>
      </body>
    </html>
  )
}
